version: "3.4"
services:
  db:
    image: ${DC_POSTGRES_IMAGE}
    environment:
      POSTGRES_USER: lavaserver
      POSTGRES_PASSWORD: lavaserverdbpass
    volumes:
    - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  lava-logs:
    image: ${DC_SERVER_IMAGE}
    volumes:
    - joboutput:/var/lib/lava-server/default/media/job-output
    - ./overlays/lava-server/etc/lava-server/instance.conf:/etc/lava-server/instance.conf:ro
    - ./overlays/lava-server/etc/lava-server/settings.conf:/etc/lava-server/settings.conf:ro
    - ./overlays/lava-server/etc/lava-server/lava-logs:/etc/lava-server/lava-logs:ro
    depends_on:
    - db
    environment:
      SERVICES: "lava-logs"
    ports:
    - 5555:5555
    restart: unless-stopped
    stop_grace_period: 20s

  lava-master:
    image: ${DC_SERVER_IMAGE}
    volumes:
    - devices:/etc/lava-server/dispatcher-config/devices:ro
    - health-checks:/etc/lava-server/dispatcher-config/health-checks:ro
    - ./overlays/lava-server/etc/lava-server/instance.conf:/etc/lava-server/instance.conf:ro
    - ./overlays/lava-server/etc/lava-server/settings.conf:/etc/lava-server/settings.conf:ro
    - ./overlays/lava-server/etc/lava-server/lava-master:/etc/lava-server/lava-master:ro
    depends_on:
    - db
    environment:
      SERVICES: "lava-master"
    ports:
    - 5556:5556
    restart: unless-stopped

  lava-publisher:
    image: ${DC_SERVER_IMAGE}
    volumes:
    - ./overlays/lava-server/etc/lava-server/instance.conf:/etc/lava-server/instance.conf:ro
    - ./overlays/lava-publisher/etc/lava-server/settings.conf:/etc/lava-server/settings.conf:ro
    environment:
      SERVICES: "lava-publisher"
    ports:
    - 5500:5500
    restart: unless-stopped

  lava-server:
    image: ${DC_SERVER_IMAGE}
    volumes:
    - devices:/etc/lava-server/dispatcher-config/devices
    - health-checks:/etc/lava-server/dispatcher-config/health-checks
    - joboutput:/var/lib/lava-server/default/media/job-output
    - ./overlays/lava-server/etc/lava-server/instance.conf:/etc/lava-server/instance.conf:ro
    - ./overlays/lava-server/etc/lava-server/settings.conf:/etc/lava-server/settings.conf:ro
    depends_on:
    - db
    environment:
      SERVICES: "gunicorn"
      BIND: "--bind lava-server:8000"
    restart: unless-stopped

  apache2:
    image: ${DC_SERVER_IMAGE}
    volumes:
    - ./overlays/lava-server/etc/apache2/sites-available/lava-server.conf:/etc/apache2/sites-available/lava-server.conf:ro
    depends_on:
    - lava-server
    environment:
      SERVICES: "apache2"
    ports:
    - 80:80
    restart: unless-stopped

  lava-dispatcher:
    build:
      context: ./dispatcher
      args:
        image: ${DC_DISPATCHER_IMAGE}
        extra_packages: "linux-image-amd64 curl"
    depends_on:
    - lava-dispatcher-webserver
    - lava-dispatcher-tftpd
    - lava-dispatcher-ser2net
    - lava-dispatcher-nfs
    hostname: worker0
    devices:
    - /dev/kvm # needed for QEMU
    - /dev/net/tun # needed for QEMU
    security_opt:
    - apparmor:unconfined # needed for usb mass storage
    cap_add:
    - NET_ADMIN # needed for QEMU
    - SYS_ADMIN # needed for usb mass storage
    environment:
      DISPATCHER_HOSTNAME: "--hostname=${DC_DISPATCHER_HOSTNAME}"
      LOGGER_URL: "tcp://${DC_LAVA_LOGS_HOSTNAME}:5555"
      MASTER_URL: "tcp://${DC_LAVA_MASTER_HOSTNAME}:5556"
      ENCRYPT: "${DC_LAVA_MASTER_ENCRYPT}"
      SOCKS_PROXY: "${DC_SOCKS_PROXY}"
      MASTER_CERT: "${DC_MASTER_CERT}"
      SLAVES_CERT: "${DC_SLAVES_CERT}"
      http_proxy: "${http_proxy}"
      https_proxy: "${https_proxy}"
      ftp_proxy: "${ftp_proxy}"
    volumes:
    - /run/udev/control:/run/udev/control:ro # libudev expects it for udev events
    - /boot:/boot:ro
    - /lib/modules:/lib/modules:ro
    - '/dev/bus:/dev/bus:ro' # required for USB devices
    - '/dev/serial:/dev/serial:ro' # required for serial adapters
    - '/dev/disk:/dev/disk:ro' # required for SDMux
    - worker-http:/var/lib/lava/dispatcher/tmp
    - worker-tftp:/srv/tftp

  lava-dispatcher-webserver:
    build:
      context: ./httpd
    ports:
      - 80
    volumes:
      - worker-http:/var/lib/lava/dispatcher/tmp

  lava-dispatcher-tftpd:
    build:
      context: ./tftpd
    environment:
      http_proxy: "${http_proxy}"
      https_proxy: "${https_proxy}"
      ftp_proxy: "${ftp_proxy}"
    ports:
        - 69:69/udp
    volumes:
      - worker-tftp:/srv/tftp

  lava-dispatcher-ser2net:
    build:
      context: ./ser2net
    environment:
      http_proxy: "${http_proxy}"
      https_proxy: "${https_proxy}"
      ftp_proxy: "${ftp_proxy}"
    privileged: true
    volumes:
      - '/dev/serial:/dev/serial' # required for serial adapters
      - '/dev:/dev'
    devices: []
    ports:
      - 7101:7101

  lava-dispatcher-nfs:
    build:
      context: ./nfs
    environment:
      http_proxy: "${http_proxy}"
      https_proxy: "${https_proxy}"
      ftp_proxy: "${ftp_proxy}"
    privileged: true
    volumes:
      - worker-http:/var/lib/lava/dispatcher/tmp
    ports:
      - 111:111
      - 111:111/udp
      - 2049:2049
      - 2049:2049/udp
      - 35543:35543

volumes:
  db-data:
    name: lava-server-pgdata
  devices:
    name: lava-server-devices
  health-checks:
    name: lava-server-health-checks
  joboutput:
    name: lava-server-joboutput
  worker-http:
  worker-tftp:
